# CONFIGURAÇÕES DO BANCO DE DADOS (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/receita_facil?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURAÇÕES JPA/HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# CONFIGURAÇÃO DE SERVER
server.port=8080

# CONFIGURAÇÃO DE LOGGING
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
